[package]
name = "teste-winapi"
version = "0.1.1"
authors = ["Nelson Junior <ircnelson@gmail.com>"]

[dependencies]
libc = "0.2.23"
kernel32-sys = "0.2.2"
winapi = "0.2.8"
num_cpus = "1.5.1"
libuv-sys = { git = "https://github.com/Meralis40/libuv-rs.git" }