[package]
name = "teste-winapi"
version = "0.1.0"
authors = ["Nelson Junior <ircnelson@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "0.2.23"
kernel32-sys = "0.2.2"
winapi = "0.2.8"
num_cpus = "1.5.1"

[build-dependencies]
gcc = "*"